import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import numpy as np
from template.prelude_template import load_polymarket_data, load_data
from typing import Dict
import logging


def differatiate_data(data: pd.DataFrame, period: int) -> pd.DataFrame:
    """
    return a de-mean-ed percentage change df of input df
    Args:    
        data: a pandas dataframe
        period: period interval, int
    return: pd.DataFrame
        percentage change of dataframe on assigned interval
        drop na, and substract mean
    """
    res = data.pct_change(periods=period, fill_method=None).dropna()
    res = res - res.mean()
    return res

def AD_Fuller_Test(data: pd.DataFrame) -> Dict:
    """
    Run Augment Dickey-Fuller test for each column of input df
    """
    from statsmodels.tsa.stattools import adfuller

    result = {}
    for col in data.columns:
        res = adfuller(data[col].dropna().values)
        result[col] = {"AD_Fuller_Statistics": res[0], "pvalue": res[1]}
    result["critic value"] = {k: np.round(v,3) for (k,v) in res[4].items()}
    return result

def vec_ar_test(data: pd.DataFrame, y: str, alpha=0.05):
    """
    Run vector auto-regressive test after stationary check and optimal lags finding
    Args:
        data: datasets;
        y: target variable;
        alpha: significance level for AD_Fuller test
    Return:
        VAR model fitting result
    """
    from statsmodels.tsa.api import VAR

    # check stationary
    adf = AD_Fuller_Test(data)
    for col in data.columns:
        if adf[col]['pvalue'] >  alpha:
            print(f"feature {col} does not pass AD_Fuller test at significance level {alpha}")
            data.drop(col, axis=1, inplace=True)
    
    # find optimal bic lags
    model = VAR(data.dropna())
    finding_lags = model.select_order(maxlags=30)
    optimal_lags = finding_lags.bic
    print(f"The optimal BIC lags number is {optimal_lags}")
    results = model.fit(maxlags=optimal_lags)

    return results

def granger_test(data: pd.DataFrame, y: str, lags: int) -> Dict:
    """
    return Granger Causality Test result of features on y;
    both features and y should be stationary;
    Args:
        data: all data include target y
        y: target column name in data
        lags: maximum lags to run test
    return:
        test results
    """
    from statsmodels.tsa.stattools import grangercausalitytests

    feature_names = data.columns
    results = {}
    for feat in feature_names:
        if feat != y:
            print(f"=====================================================================\nTesting Granger Causality from {feat} to {y}")
            gc = grangercausalitytests(data[[feat, y]], maxlag=lags)
            results[feat] = gc
    return results

def johansen_coint_test(data:pd.DataFrame, det_order=0, k_ar_diff=1):
    """
    Run Johansen cointegration test
    Args:
        data: should contain no more than 12 variables
    Return:
        coint_rank: int
        result: Johansen cointegration test result
    """
    from statsmodels.tsa.vector_ar.vecm import coint_johansen

    result = coint_johansen(data, det_order=det_order, k_ar_diff=k_ar_diff)

    # for i in range(len(data.columns)):
    #     print(f"Rank {i}: trace={result.lr1[i]:.3f}, critical={result.cvt[i, 1]:.3f}")
    
    # for i in range(len(data.columns)):
    #     print(f"Rank {i}: max eig={result.lr2[i]:.3f}, critical={result.cvm[i, 1]:.3f}")
    
    coint_rank = "Not defined"
    for r in range(len(data.columns)):
        if result.lr1[r] < result.cvt[r, 1]:  
            coint_rank = r
            break
            
    return coint_rank, result

def vecm(data:pd.DataFrame, r:int):
    """
    Run VECM model fitting
    Arges:
        data: contains no more than 12 variables; should be same data for coint_test;
        r: cointegration rank obtained from coint_test
    return:
        fitted model
    """
    from statsmodels.tsa.vector_ar.vecm import VECM, select_order
    
    lag_selection = select_order(data, maxlags=30, deterministic='co')
    optimal_lags = lag_selection.bic
    print(f"Optimal lag length for VAR: {optimal_lags}")
    print(f"VECM will use {optimal_lags - 1} lags of differences")

    vecm_model = VECM(
        endog=data,
        k_ar_diff=optimal_lags - 1,  
        coint_rank=r,                
        deterministic='co'           
    )
    
    return vecm_model.fit()

def interpret_vecm_results(vecm_result):
    """
    This function is generated by DeepSeek.
    explain VECM results
    """
    
    var_names = vecm_result.names
    n_vars = len(var_names)
    target_idx = var_names.index('PriceUSD_coinmetrics')
    print("=" * 70)
    print("1. erro correction efficient towards long term equilibrium）")
    
    alpha = vecm_result.alpha
    alpha_pvalues = vecm_result.pvalues_alpha
    if alpha.ndim == 1:
        alpha = alpha.reshape(-1, 1)
    if alpha_pvalues.ndim == 1:
        alpha_pvalues = alpha_pvalues.reshape(-1, 1)
    
    alpha_data = []
    for i in range(n_vars):
        for j in range(alpha.shape[1]):
            alpha_data.append({
                'Variable': var_names[i],
                'Cointegrating_Vector': f"EC{j+1}",
                'Alpha': alpha[i, j],
                'Std_Error': vecm_result.stderr_alpha[i, j] if hasattr(vecm_result, 'stderr_alpha') else np.nan,
                'P_Value': alpha_pvalues[i, j] if alpha_pvalues.shape[1] > j else np.nan
            })
    
    alpha_df = pd.DataFrame(alpha_data)    
    alpha_df['Significance'] = alpha_df['P_Value'].apply(
        lambda x: '***' if x < 0.01 else '**' if x < 0.05 else '*' if x < 0.1 else '' if pd.notna(x) else ''
    )
    print(f"\ntotal of {alpha.shape[1]} erro correction items (cointegration relationships)")
    print("\nerro correction coeficients:")
    print(alpha_df.to_string(index=False))
    
    print("\n" + "=" * 70)
    print(f"2. short term correction equation - {var_names[target_idx]}")
    print("=" * 70)
    
    gamma = vecm_result.gamma
    gamma_pvalues = vecm_result.pvalues_gamma if hasattr(vecm_result, 'pvalues_gamma') else None    
    print(f"\nΔ{var_names[target_idx]}_t short term dynamics:")
    for i, var in enumerate(var_names):
        if gamma_pvalues is not None and gamma_pvalues[target_idx, i] < 0.1:
            sig = '***' if gamma_pvalues[target_idx, i] < 0.01 else \
                  '**' if gamma_pvalues[target_idx, i] < 0.05 else '*'
            print(f"  Δ{var}_t-1: {gamma[target_idx, i]:.6f} (p={gamma_pvalues[target_idx, i]:.4f}) {sig}")
        elif gamma_pvalues is None:
            print(f"  Δ{var}_t-1: {gamma[target_idx, i]:.6f}")
    
    print("\n" + "=" * 70)
    print("3. cointegration vectors (Long term equilibrium)")
    print("=" * 70)   
    beta = vecm_result.beta
    print(f"total of {beta.shape[1]} cointegration relationships")
    
    price_idx = target_idx    
    for r in range(min(6, beta.shape[1])):  
        print(f"\ncointegration {r+1} (after normalisation):")        
        beta_vec = beta[:, r].copy()        
        if abs(beta_vec[price_idx]) > 1e-10:
            beta_vec = beta_vec / abs(beta_vec[price_idx])
        
        coint_df = pd.DataFrame({
            'Variable': var_names,
            'Coefficient': beta_vec
        })
        coint_df['Abs_Coefficient'] = abs(coint_df['Coefficient'])
        coint_df = coint_df.sort_values('Abs_Coefficient', ascending=False)
        
        print("  long term equilibrium:")
        eq_terms = []
        for _, row in coint_df.iterrows():
            if abs(row['Coefficient']) > 0.01: 
                if row['Variable'] == var_names[price_idx]:
                    eq_terms.append(f"{row['Variable']}")
                else:
                    sign = "+" if row['Coefficient'] > 0 else "-"
                    eq_terms.append(f"{sign} {abs(row['Coefficient']):.4f}*{row['Variable']}")    
        print("  0 =", " ".join(eq_terms))
    
    print("\n" + "=" * 70)
    print("4. significant correction items")
    print("=" * 70)
    
    ec1_idx = 0    
    adjusting_vars = []
    for i in range(n_vars):
        p_val = alpha_pvalues[i, ec1_idx] if alpha_pvalues.shape[1] > ec1_idx else 1.0
        if p_val < 0.05:
            adjusting_vars.append({
                'Variable': var_names[i],
                'Alpha': alpha[i, ec1_idx],
                'P_Value': p_val,
                'Significance': '***' if p_val < 0.01 else '**' if p_val < 0.05 else '*'
            })
    
    if adjusting_vars:
        adj_df = pd.DataFrame(adjusting_vars)
        adj_df['Direction'] = adj_df['Alpha'].apply(
            lambda x: '↓ downwards' if x < 0 else '↑ upwards'
        )
        adj_df = adj_df.sort_values('Alpha', key=abs, ascending=False)
        print(f"\nsignificant correction variables of first cointegration:")
        print(adj_df[['Variable', 'Alpha', 'Direction', 'P_Value', 'Significance']].to_string(index=False))
        
        price_adj = adj_df[adj_df['Variable'] == var_names[target_idx]]
        if not price_adj.empty:
            print(f"\n✓ Bitcoin Price Adjusting!")
            print(f"  Speed: {price_adj['Alpha'].values[0]:.4f}")
            print(f"  Direction: {price_adj['Direction'].values[0]}")
            print(f"  Decay: {abs(np.log(0.5) / abs(price_adj['Alpha'].values[0])):.2f} 期")
        else:
            print(f"\n✗ Bitcoin Price Not Adjusting")
            print(f"  Other variables Follow Bitcoin Price Change")
    else:
        print("No significant Adjusting, check if long term equilibrium achieved")
    
    return alpha_df, beta

def acf_pacf_plot(data: pd.DataFrame, lags=60):
    """
    Run acf/pacf test and plot acf/pacf lags of given DataFrame
    Args: 
        data: pd.DataFrame;
        lags: int;
    Return: 
        dict: acf/pacf test for each column of data
        plot: figure
    """
    from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
    from statsmodels.tsa.stattools import acf, pacf

    figure, ax = plt.subplots(len(data.columns), 2, figsize = (2*4, len(data.columns)*2))
    k = 0
    results = {}
    for col in data.columns:
        # i,_ = coordinates[k]
        acf_values, acf_conf_intervals = acf(data[col], 
                                             nlags=lags, 
                                             alpha=0.05, 
                                             fft=True)
        plot_acf(data[col].dropna().values, 
                 lags=lags, 
                 ax=ax[k][0], 
                 zero=False, 
                 title=f'{col} ACF', 
                 auto_ylims=True)

        pacf_values, pacf_conf_intervals = pacf(data[col].dropna().values, 
                                                nlags=lags, 
                                                alpha=0.05, 
                                                method='ywm')
        plot_pacf(data[col].dropna().values, 
                  lags=lags, 
                  ax=ax[k][1], 
                  zero=False, 
                  title=f'{col} PACF', 
                  auto_ylims=True)
        results[col] = {"acf":{
                                "Lag": range(lags+1),
                                "ACF": acf_values,
                                "Lower_CI": acf_conf_intervals[:, 0],
                                "Upper_CI": acf_conf_intervals[:, 1]
                                },
                        "pacf":{
                                "Lag": range(lags+1),
                                "PACF": pacf_values, 
                                "Lower_CI": pacf_conf_intervals[:, 0],
                                "Upper_CI": pacf_conf_intervals[:, 1]
                                }
                        }
        k += 1
    plt.tight_layout()
    plt.show() 
    return results, figure

def compute_plot_coor(data: pd.DataFrame,):
    """
    compute coorelation matrix and plot heat map of this corr_matrix
    Args:
        dataframe
    Return:
        coorelation matrix and heat map figure
    """
    corr = data.corr()
    figure, ax = plt.subplots(figsize=(8,8))
    sns.heatmap(corr, annot=False, cmap="coolwarm", fmt=".2f")
    plt.title("Correlation Matrix")
    plt.tight_layout()
    plt.show()

    return corr, figure

def plot_ts(data: pd.DataFrame):
    """
    plot time series with a proper grid layout
    the input dataframe should has more than 3 columns
    """
    n = len(data.columns)
    j, i = int(np.floor(np.sqrt(n))), int(n // np.floor(np.sqrt(n)) + 1)
    coordinates = [[k, l] for k in range(i) for l in range(j)]
    fig, ax = plt.subplots(i, j, figsize=(j*6, i*6))
    k = 0
    for col in data.columns:
        i, j = coordinates[k]
        ax[i][j].plot(data[col])
        ax[i][j].set_title(col)
        k += 1
    plt.show()
    return fig

class POLY():
    def __init__(self, btc_only=True):
        """
        Args:
            if btc_only, then btc relevant questions will be selected;
            otherwise, all crypto question will be selected
        """
        poly = load_polymarket_data()
        self.btc_only = btc_only
        self.MARKETS = poly['markets']
        self.TOKENS = poly['tokens']
        self.ODDS = poly['odds_history']
           
    def _separate_market_df(self):
        """
        separate poly dataframes for feature extraction
        """

        # markets - as volume info only available in markets df (trades are from 2025)
        if self.btc_only:
            btc_markets_df = self.MARKETS[self.MARKETS['question'].str.contains("Bitcoin|BTC|btc",
                                                                                 case=False,
                                                                                 na=False)].copy()
            logging.info("processing bitcoin only market data")
        else:
            btc_markets_df = self.MARKETS[self.MARKETS['question'].str.contains("Bitcoin|BTC|btc|ETH|Ethereum|Solana|Crypto|Coin|Blockchain",
                                                                                 case=False, 
                                                                                 na=False)]
            logging.info("processing all crypto market data")
        btc_markets_df['created_at'] = pd.to_datetime(btc_markets_df['created_at']).dt.normalize()

        # separate bidding direction - bid up, bid down, neutral
        btc_mkt_downs = btc_markets_df[btc_markets_df['question'].str.contains("less|lower|dip",
                                                                                case=False, 
                                                                                na=False)].copy()
        new_df = btc_markets_df[~btc_markets_df['market_id'].isin(btc_mkt_downs['market_id'])]
        btc_mkt_ups = new_df[new_df['question'].str.contains("greater|Up|above|hit|reach|break", 
                                                                             case=False, 
                                                                             na=False)].copy()

        btc_mkt_neutrals = new_df[~new_df['market_id'].isin(btc_mkt_ups['market_id'])].copy()

        # direction column
        btc_mkt_ups['direction'] = 1
        btc_mkt_downs['direction'] = -1
        btc_mkt_neutrals['direction'] = 0

        return btc_mkt_ups, btc_mkt_downs, btc_mkt_neutrals

    def _merge_token_odds(self, markets:pd.DataFrame):
        """
        add corresponding token and odds message to markets dataframe
        """
        # find all tokens of each market_id and choose the first token_id
        # for binary questions , the first token_id means prob of 'Yes'
        tokens = self.TOKENS[
                        self.TOKENS['market_id'].isin(markets['market_id'])
                        ].drop_duplicates(
                            subset=['market_id'], 
                            keep='first')
        # markets['token_id'] = markets['market_id'].apply(lambda x : tokens[tokens['market_id']==x].iloc[0]['token_id']) -> slower than merge
        res = pd.merge(left=markets, 
                       right=tokens, 
                       how='left', 
                       left_on=['market_id'], 
                       right_on=['market_id'])

        # merge odds price (a probability) on same market_id and token_id
        # same combination of ['market_id', 'token_id'] may has multiple price(prob), we choose the mean of them
        ## since (1) volume info missed in TOKENS and ODDS dfs. (2) there is no reason for arbitrary selection.
        odds = self.ODDS[
                        self.ODDS['market_id'].isin(markets['market_id'])][
                            ['market_id', 'token_id', 'price']
                                ].drop_duplicates(
                                    subset=['market_id'], 
                                    keep='first')
        res = pd.merge(left=res, 
                       right=odds, 
                       how='left', 
                       left_on=['market_id', 'token_id'], 
                       right_on=['market_id', 'token_id'])
        res.fillna({'price':0.5}, inplace=True)
        res = res.groupby('token_id').agg(
                            market_id=('market_id','min'),
                            question=('question','min'),
                            created_at=('created_at','min'),
                            end_date=('end_date','min'),
                            volume=('volume', 'mean'),
                            direction=('direction', 'min'),
                            price=('price','mean')
                        ).reset_index()

        return res
    
    def _prepare_dfs(self):
        ups, downs, neutrals = self._separate_market_df()
        ups = self._merge_token_odds(ups)
        downs = self._merge_token_odds(downs)
        neutrals = self._merge_token_odds(neutrals)
        res = pd.concat([ups, downs, neutrals]).sort_values('created_at')
        res['weighted_volume'] = res['volume'] * res['direction'] * res['price'] * 2

        return res
    
    def prepare_features(self, use_benchmark=False):
        """
        prepare polymarket features based on markets counts and volumes
        if use_benchmark, use Trilemma's template and original volumes;
        otherwise use Trilemma's method with weighted volumes
        """
        df = self._prepare_dfs()
        if use_benchmark:
            logging.info("preparing polymarket features on Trilemma's method and original volume")
        else:
            df.drop('volume', axis=1, inplace=True)
            df.rename(columns={'weighted_volume': 'volume'}, inplace=True)
            logging.info("preparing polymarket faeatures on Trilemma's method and weighted volume")

        daily_stats = df.groupby('created_at').agg(
            daily_market_count=('market_id', 'count'),
            daily_volume=('volume', 'sum')
        ).reset_index()
        daily_stats['created_at'] = pd.to_datetime(daily_stats['created_at']).dt.normalize()
        daily_stats = daily_stats.set_index('created_at').sort_index()
        daily_stats["market_count_pct"] = (
            daily_stats["daily_market_count"]
            .rolling(30, min_periods=1)
            .apply(lambda x: (x.iloc[-1] > x[:-1]).sum() / max(len(x) - 1, 1) if len(x) > 1 else 0.5)
        )
        daily_stats["volume_pct"] = (
            daily_stats["daily_volume"]
            .rolling(30, min_periods=1)
            .apply(lambda x: (x.iloc[-1] > x[:-1]).sum() / max(len(x) - 1, 1) if len(x) > 1 else 0.5)
        )

        # match btc price data
        logging.info("matching bitcoin price data from coinmetrics dataset")
        btc = load_data()
        btc = btc.loc[daily_stats.index.min():]
        daily_stats = pd.merge(left=btc[['PriceUSD_coinmetrics', 'CapMVRVCur']], 
                               right=daily_stats, 
                               how='left',
                               left_index=True,
                               right_index=True).ffill() # forward fill for discontinuity of market data
        daily_stats['price_pct'] = (
            daily_stats['PriceUSD_coinmetrics']
            .rolling(30, min_periods=1)
            .apply(lambda x: (x.iloc[-1] > x[:-1]).sum() / max(len(x) - 1, 1) if len(x) > 1 else 0.5)
        )
        daily_stats['MVRV_pct'] = (
            daily_stats['CapMVRVCur']
            .rolling(30, min_periods=1)
            .apply(lambda x : (x[-1] > x[:-1]).sum() / max(len(x) - 1, 1) if len(x) > 1 else 0.5)
        )
        return daily_stats
    

